# Generated by Django 5.1.2 on 2025-11-05 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["is_published", "start_date"],
                name="events_even_is_publ_08e85a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["is_published", "created_at"],
                name="events_even_is_publ_4b37ca_idx",
            ),
        ),
    ]
