# Generated by Django 5.1.2 on 2025-11-05 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
        ("members", "0002_memberbadge_member_is_verified_member_verified_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="member",
            field=models.ForeignKey(
                blank=True,
                help_text="Member profile linked to this payment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="members.member",
                verbose_name="member",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional payment notes", verbose_name="notes"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                blank=True,
                help_text="e.g., Stripe, PayPal, Bank Transfer, Manual",
                max_length=50,
                verbose_name="payment method",
            ),
        ),
    ]
