# Generated by Django 5.1.2 on 2025-11-01 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "membership_number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("alumni", "Alumni"),
                            ("honorary", "Honorary Member"),
                        ],
                        default="student",
                        max_length=10,
                    ),
                ),
                (
                    "university",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="university"
                    ),
                ),
                (
                    "course",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="course of study"
                    ),
                ),
                (
                    "year_of_study",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="year of study"
                    ),
                ),
                (
                    "graduation_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="graduation year"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="city"),
                ),
                (
                    "country_of_origin",
                    models.CharField(
                        default="Cameroon",
                        max_length=100,
                        verbose_name="country of origin",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of birth"
                    ),
                ),
                (
                    "joined_date",
                    models.DateField(auto_now_add=True, verbose_name="joined date"),
                ),
                (
                    "membership_expiry",
                    models.DateField(
                        blank=True, null=True, verbose_name="membership expiry"
                    ),
                ),
                (
                    "profile_public",
                    models.BooleanField(default=True, verbose_name="public profile"),
                ),
                (
                    "email_public",
                    models.BooleanField(default=False, verbose_name="public email"),
                ),
                ("linkedin", models.URLField(blank=True, verbose_name="LinkedIn")),
                ("website", models.URLField(blank=True, verbose_name="website")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "member",
                "verbose_name_plural": "members",
                "ordering": ["-joined_date"],
            },
        ),
    ]
