# Generated by Django 5.1.2 on 2025-11-05 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon class name (e.g., 'icon-star', 'icon-trophy')",
                        max_length=50,
                        verbose_name="icon",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("membership", "Membership"),
                            ("activity", "Activity"),
                            ("achievement", "Achievement"),
                            ("special", "Special"),
                        ],
                        default="achievement",
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "badge",
                "verbose_name_plural": "badges",
                "ordering": ["category", "name"],
            },
        ),
        migrations.AddField(
            model_name="member",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="is verified"),
        ),
        migrations.AddField(
            model_name="member",
            name="verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="verified at"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_members",
                to=settings.AUTH_USER_MODEL,
                verbose_name="verified by",
            ),
        ),
        migrations.CreateModel(
            name="MemberApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="application date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about the application",
                        verbose_name="notes",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reviewed at"
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes from the reviewer",
                        verbose_name="review notes",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reviewed by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "member application",
                "verbose_name_plural": "member applications",
                "ordering": ["-application_date"],
            },
        ),
        migrations.CreateModel(
            name="MemberAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "earned_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="earned date"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about earning this badge",
                        verbose_name="notes",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="members.member",
                        verbose_name="member",
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="members.memberbadge",
                        verbose_name="badge",
                    ),
                ),
            ],
            options={
                "verbose_name": "member achievement",
                "verbose_name_plural": "member achievements",
                "ordering": ["-earned_date"],
                "unique_together": {("member", "badge")},
            },
        ),
    ]
