# Generated by Django 5.1.2 on 2025-11-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailedLoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        db_index=True, verbose_name="IP address"
                    ),
                ),
                (
                    "attempted_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="attempted at"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
            ],
            options={
                "verbose_name": "failed login attempt",
                "verbose_name_plural": "failed login attempts",
                "ordering": ["-attempted_at"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="verification_token_created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="verification token created at"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="accounts_us_email_74c8d6_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "role"], name="accounts_us_is_acti_c6d74b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["date_joined"], name="accounts_us_date_jo_ff39bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["verification_token_created_at"],
                name="accounts_us_verific_e25741_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="failedloginattempt",
            index=models.Index(
                fields=["email", "attempted_at"], name="accounts_fa_email_77615e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="failedloginattempt",
            index=models.Index(
                fields=["ip_address", "attempted_at"],
                name="accounts_fa_ip_addr_f660ca_idx",
            ),
        ),
    ]
