# Generated by Django 5.1.2 on 2025-11-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_admin_message",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this message is from an admin or board member",
                verbose_name="Is admin message",
            ),
        ),
    ]
