# Generated by Django 5.1.2 on 2025-11-05 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="newspost",
            index=models.Index(
                fields=["is_published", "created_at"],
                name="news_newspo_is_publ_ac0176_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="newspost",
            index=models.Index(
                fields=["is_published", "visibility"],
                name="news_newspo_is_publ_ec3595_idx",
            ),
        ),
    ]
