# Generated by Django 5.1.2 on 2025-11-01 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(verbose_name="description")),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="company name"),
                ),
                ("location", models.CharField(max_length=200, verbose_name="location")),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("internship", "Internship"),
                            ("contract", "Contract"),
                            ("temporary", "Temporary"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum salary (optional)",
                        max_digits=10,
                        null=True,
                        verbose_name="minimum salary",
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum salary (optional)",
                        max_digits=10,
                        null=True,
                        verbose_name="maximum salary",
                    ),
                ),
                (
                    "requirements",
                    models.TextField(blank=True, verbose_name="requirements"),
                ),
                (
                    "posted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="posted at"),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="application deadline"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="views"),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_postings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="posted by",
                    ),
                ),
            ],
            options={
                "verbose_name": "job posting",
                "verbose_name_plural": "job postings",
                "ordering": ["-posted_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cover_letter",
                    models.TextField(blank=True, verbose_name="cover letter"),
                ),
                (
                    "resume",
                    models.FileField(
                        help_text="Upload your resume (PDF, DOC, or DOCX, max 10MB)",
                        upload_to="resumes/",
                        verbose_name="resume",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewed", "Under Review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="applied at"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reviewed at"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes for the employer",
                        verbose_name="notes",
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="applicant",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.jobposting",
                        verbose_name="job",
                    ),
                ),
            ],
            options={
                "verbose_name": "job application",
                "verbose_name_plural": "job applications",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["-posted_at"], name="jobs_jobpos_posted__b98875_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["job_type"], name="jobs_jobpos_job_typ_fa6fc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["location"], name="jobs_jobpos_locatio_73bd90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["is_active"], name="jobs_jobpos_is_acti_6314b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["-applied_at"], name="jobs_jobapp_applied_ab7064_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(fields=["status"], name="jobs_jobapp_status_8c3944_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="jobapplication",
            unique_together={("job", "applicant")},
        ),
    ]
