# Generated by Django 5.1.2 on 2025-11-05 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["is_active", "posted_at"], name="jobs_jobpos_is_acti_a445c2_idx"
            ),
        ),
    ]
