# Generated by Django 5.1.1 on 2025-11-16 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("general", "General Inquiries"),
                            ("students", "Student Support"),
                            ("membership", "Membership"),
                            ("partnerships", "Partnerships"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Contact Type",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display label (e.g., 'General Inquiries')",
                        max_length=200,
                        verbose_name="Label",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Phone Number"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Display Order"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Contact Information",
                "verbose_name_plural": "Contact Information",
                "ordering": ["display_order", "contact_type"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Program Name")),
                ("description", models.TextField(verbose_name="Description")),
                ("url", models.URLField(blank=True, verbose_name="Program URL")),
                (
                    "icon",
                    models.CharField(
                        default="exchange",
                        help_text="Icon identifier (e.g., 'erasmus', 'exchange', 'study-abroad')",
                        max_length=50,
                        verbose_name="Icon Name",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Display Order"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Exchange Program",
                "verbose_name_plural": "Exchange Programs",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="University Name"),
                ),
                ("url", models.URLField(blank=True, verbose_name="Website URL")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Location"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="universities/logos/",
                        verbose_name="Logo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Lower numbers appear first",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "University",
                "verbose_name_plural": "Universities",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="UsefulLinkCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Category Name"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Display Order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Link Category",
                "verbose_name_plural": "Link Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="OfficeHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        max_length=20,
                        verbose_name="Day",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="Closed"),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Public Reception'",
                        max_length=200,
                        verbose_name="Notes",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Display Order"),
                ),
            ],
            options={
                "verbose_name": "Office Hour",
                "verbose_name_plural": "Office Hours",
                "ordering": ["display_order", "day"],
                "unique_together": {("day", "start_time")},
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name if not linked to a member",
                        max_length=200,
                        verbose_name="Name",
                    ),
                ),
                (
                    "university",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="University"
                    ),
                ),
                ("content", models.TextField(verbose_name="Testimonial Content")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="testimonials/photos/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Featured"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Display Order"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="testimonials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UsefulLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Link Name")),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional icon identifier",
                        max_length=50,
                        verbose_name="Icon Name",
                    ),
                ),
                (
                    "is_external",
                    models.BooleanField(
                        default=True,
                        help_text="Opens in new tab",
                        verbose_name="External Link",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Display Order"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="content.usefullinkcategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Useful Link",
                "verbose_name_plural": "Useful Links",
                "ordering": ["category", "display_order", "name"],
            },
        ),
    ]
