# Generated by Django 5.1.1 on 2025-11-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Featured image of the university (recommended: 800x600px)",
                null=True,
                upload_to="universities/images/",
                verbose_name="University Image",
            ),
        ),
        migrations.AlterField(
            model_name="university",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="University logo (recommended: 200x200px)",
                null=True,
                upload_to="universities/logos/",
                verbose_name="Logo",
            ),
        ),
    ]
