# Generated by Django 5.1.1 on 2025-11-19 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_university_image_alter_university_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactFormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("general", "General Inquiries"),
                            ("students", "Student Support"),
                            ("membership", "Membership"),
                            ("partnerships", "Partnerships"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Contact Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("responded", "Responded"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        help_text="Email address where the message was sent",
                        max_length=254,
                        verbose_name="Recipient Email",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="User Agent"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes for staff",
                        verbose_name="Internal Notes",
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Responded At"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_responses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responded By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Form Submission",
                "verbose_name_plural": "Contact Form Submissions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="content_con_created_e94976_idx"
                    ),
                    models.Index(
                        fields=["status"], name="content_con_status_ca76cc_idx"
                    ),
                    models.Index(
                        fields=["contact_type"], name="content_con_contact_666d3e_idx"
                    ),
                ],
            },
        ),
    ]
