# Generated by Django 5.1.2 on 2025-11-01 16:09

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="name"),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "color",
                    models.CharField(
                        default="#007bff",
                        help_text="Hex color code",
                        max_length=7,
                        verbose_name="color",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "document tag",
                "verbose_name_plural": "document tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("slug", models.SlugField(max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "default_access_level",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("members", "Members Only"),
                            ("board", "Board Only"),
                            ("admin", "Admin Only"),
                        ],
                        default="members",
                        max_length=10,
                        verbose_name="default access level",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_folders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="documents.documentfolder",
                        verbose_name="parent folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "document folder",
                "verbose_name_plural": "document folders",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        upload_to=apps.documents.models.document_upload_path,
                        verbose_name="file",
                    ),
                ),
                (
                    "version_number",
                    models.DecimalField(
                        decimal_places=1,
                        default=1.0,
                        max_digits=5,
                        verbose_name="version number",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, verbose_name="file size"),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MIME type"
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("public", "Public"),
                            ("members", "Members Only"),
                            ("board", "Board Only"),
                            ("admin", "Admin Only"),
                        ],
                        help_text="Leave blank to inherit from folder",
                        max_length=10,
                        null=True,
                        verbose_name="access level",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="published"),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="download count"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploader",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="documents.documentfolder",
                        verbose_name="folder",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="documents",
                        to="documents.documenttag",
                        verbose_name="tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "document",
                "verbose_name_plural": "documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission_type",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("download", "Download"),
                            ("edit", "Edit"),
                            ("delete", "Delete"),
                        ],
                        max_length=10,
                        verbose_name="permission type",
                    ),
                ),
                ("granted", models.BooleanField(default=True, verbose_name="granted")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="documents.document",
                        verbose_name="document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "document permission",
                "verbose_name_plural": "document permissions",
                "ordering": ["document", "user"],
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.DecimalField(
                        decimal_places=1, max_digits=5, verbose_name="version number"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        upload_to=apps.documents.models.version_upload_path,
                        verbose_name="file",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, verbose_name="file size"),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MIME type"
                    ),
                ),
                (
                    "changelog",
                    models.TextField(
                        blank=True,
                        help_text="What changed in this version",
                        verbose_name="changelog",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_versions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.document",
                        verbose_name="document",
                    ),
                ),
            ],
            options={
                "verbose_name": "document version",
                "verbose_name_plural": "document versions",
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="FolderPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission_type",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("create", "Create Documents"),
                            ("edit", "Edit"),
                            ("delete", "Delete"),
                        ],
                        max_length=10,
                        verbose_name="permission type",
                    ),
                ),
                ("granted", models.BooleanField(default=True, verbose_name="granted")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="documents.documentfolder",
                        verbose_name="folder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folder_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "folder permission",
                "verbose_name_plural": "folder permissions",
                "ordering": ["folder", "user"],
            },
        ),
        migrations.AddIndex(
            model_name="documentfolder",
            index=models.Index(
                fields=["parent", "name"], name="documents_d_parent__c8f9de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentfolder",
            index=models.Index(fields=["slug"], name="documents_d_slug_9cd839_idx"),
        ),
        migrations.AddConstraint(
            model_name="documentfolder",
            constraint=models.UniqueConstraint(
                fields=("parent", "slug"), name="unique_folder_slug_per_parent"
            ),
        ),
        migrations.AddIndex(
            model_name="documentpermission",
            index=models.Index(
                fields=["document", "user"], name="documents_d_documen_0435ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentpermission",
            index=models.Index(
                fields=["user", "permission_type"],
                name="documents_d_user_id_54c952_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentpermission",
            constraint=models.UniqueConstraint(
                fields=("document", "user", "permission_type"),
                name="unique_document_user_permission",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["folder", "-created_at"], name="documents_d_folder__28f747_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["uploader", "-created_at"],
                name="documents_d_uploade_782ce1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["title"], name="documents_d_title_ccf306_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["is_published"], name="documents_d_is_publ_8c6fb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentversion",
            index=models.Index(
                fields=["document", "-version_number"],
                name="documents_d_documen_654958_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(
                fields=("document", "version_number"),
                name="unique_version_per_document",
            ),
        ),
        migrations.AddIndex(
            model_name="folderpermission",
            index=models.Index(
                fields=["folder", "user"], name="documents_f_folder__f66c45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="folderpermission",
            index=models.Index(
                fields=["user", "permission_type"],
                name="documents_f_user_id_e328e5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="folderpermission",
            constraint=models.UniqueConstraint(
                fields=("folder", "user", "permission_type"),
                name="unique_folder_user_permission",
            ),
        ),
    ]
