# Generated by Django 5.1.2 on 2025-11-05 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["is_published", "created_at"],
                name="documents_d_is_publ_b12a83_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["is_published", "folder"], name="documents_d_is_publ_c43555_idx"
            ),
        ),
    ]
