# Generated by Django 5.1.2 on 2025-11-01 15:56

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("slug", models.SlugField(unique=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="CSS class for icon",
                        max_length=50,
                        verbose_name="icon",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "can_view",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("board", "Board Member"),
                            ("member", "Member"),
                            ("public", "Public"),
                        ],
                        default="public",
                        max_length=10,
                    ),
                ),
                (
                    "can_post",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("board", "Board Member"),
                            ("member", "Member"),
                            ("public", "Public"),
                        ],
                        default="member",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("content", ckeditor.fields.RichTextField(verbose_name="content")),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="pinned"),
                ),
                (
                    "is_locked",
                    models.BooleanField(default=False, verbose_name="locked"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=True, verbose_name="approved"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="views"),
                ),
                (
                    "reply_count",
                    models.PositiveIntegerField(default=0, verbose_name="replies"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="last activity"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags",
                        max_length=200,
                        verbose_name="tags",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to="forums.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "thread",
                "verbose_name_plural": "threads",
                "ordering": ["-is_pinned", "-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", ckeditor.fields.RichTextField(verbose_name="content")),
                (
                    "is_approved",
                    models.BooleanField(default=True, verbose_name="approved"),
                ),
                (
                    "is_edited",
                    models.BooleanField(default=False, verbose_name="edited"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_reply",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_replies",
                        to="forums.reply",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="forums.thread",
                    ),
                ),
            ],
            options={
                "verbose_name": "reply",
                "verbose_name_plural": "replies",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserBan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(verbose_name="reason")),
                (
                    "ban_type",
                    models.CharField(
                        choices=[
                            ("temporary", "Temporary"),
                            ("permanent", "Permanent"),
                        ],
                        default="temporary",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="start date"),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="end date"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "banned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bans_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user ban",
                "verbose_name_plural": "user bans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "vote_type",
                    models.CharField(
                        choices=[("upvote", "Upvote"), ("downvote", "Downvote")],
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "vote",
                "verbose_name_plural": "votes",
            },
        ),
        migrations.CreateModel(
            name="Flag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("inappropriate", "Inappropriate Content"),
                            ("harassment", "Harassment"),
                            ("copyright", "Copyright Violation"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewed", "Reviewed"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reviewed at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags_reported",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flags_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "flag",
                "verbose_name_plural": "flags",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="forums_flag_status_d89f9c_idx"
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="forums_flag_content_87a768_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ModeratorAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("edit", "Edit"),
                            ("delete", "Delete"),
                            ("lock", "Lock Thread"),
                            ("unlock", "Unlock Thread"),
                            ("pin", "Pin Thread"),
                            ("unpin", "Unpin Thread"),
                            ("approve", "Approve Content"),
                            ("reject", "Reject Content"),
                            ("ban_user", "Ban User"),
                            ("unban_user", "Unban User"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("reason", models.TextField(blank=True, verbose_name="reason")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderator_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "moderator action",
                "verbose_name_plural": "moderator actions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["moderator"], name="forums_mode_moderat_e89ca4_idx"
                    ),
                    models.Index(
                        fields=["action_type"], name="forums_mode_action__145396_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("reply", "Reply"),
                            ("mention", "Mention"),
                            ("vote", "Vote"),
                            ("moderation", "Moderation"),
                            ("thread_locked", "Thread Locked"),
                            ("thread_pinned", "Thread Pinned"),
                            ("approved", "Content Approved"),
                            ("rejected", "Content Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("message", models.TextField(verbose_name="message")),
                ("is_read", models.BooleanField(default=False, verbose_name="read")),
                (
                    "is_emailed",
                    models.BooleanField(default=False, verbose_name="emailed"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="forums_noti_recipie_4c554d_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="forums_noti_created_ff5982_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["-last_activity"], name="forums_thre_last_ac_2f2a5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["category"], name="forums_thre_categor_4deee9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["author"], name="forums_thre_author__cd6798_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reply",
            index=models.Index(
                fields=["thread", "created_at"], name="forums_repl_thread__b97d59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reply",
            index=models.Index(
                fields=["author"], name="forums_repl_author__ccbe68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userban",
            index=models.Index(
                fields=["user", "is_active"], name="forums_user_user_id_420abb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="forums_vote_content_50b651_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("content_type", "object_id", "user")},
        ),
    ]
