# Generated by Django 5.1.2 on 2025-11-05 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forums", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["category", "is_approved", "-last_activity"],
                name="forums_thre_categor_63b24d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["is_approved", "-created_at"],
                name="forums_thre_is_appr_a84c93_idx",
            ),
        ),
    ]
